repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.10
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest-check
        types: [python]
        name: pytest-check
        entry: python -m pytest -v tests/ -m "not integration"
        language: system
        pass_filenames: false
        always_run: true
